apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: san-diego-infra
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: source-repository
    namespace: default
  path: ./clusters/san-diego/infra
  prune: true
  wait: true
  timeout: 10m
