apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: notification-sink-alert-info
  namespace: default
spec:
  summary: "'notification-sink-alert-error'"
  providerRef:
    name: notification-sink-provider
eventSeverity: error
eventSources:
- kind: GitRepository
  namespace: default
  name: "'*'"
- kind: Kustomization
  namespace: default
  name: "'*'"
